# Generated by Django 5.1.1 on 2024-10-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount_user', '0002_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
