# Generated by Django 5.1.1 on 2024-11-05 23:20

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'База', 'verbose_name_plural': 'База'},
        ),
        migrations.AlterModelOptions(
            name='materials',
            options={'verbose_name': 'Для аккредитации', 'verbose_name_plural': 'Для аккредитации'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организации', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={'verbose_name': 'Специалисты', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда анонс был создан.', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(help_text='Полное описание анонса, содержащее все основные сведения.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение, которое будет представлять анонс.', null=True, upload_to='announcements/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(help_text='Основной заголовок анонса. Будет отображаться на сайте.', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='base',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Полный текст подраздела, отформатированный с помощью редактора.', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='base',
            name='published',
            field=models.BooleanField(default=False, help_text='Отметьте, если информация должна быть доступна на сайте.', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='base',
            name='section',
            field=models.IntegerField(help_text='Номер раздела, связанного с базой информации для специалистов.', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='base',
            name='title',
            field=models.CharField(help_text='Название подраздела с информацией для специалистов.', max_length=255, verbose_name='Название подраздела'),
        ),
        migrations.AlterField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время публикации события.', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(help_text='Полное описание события с деталями и важной информацией.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение, представляющее событие.', null=True, upload_to='event_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(help_text='Основной заголовок события, который будет отображаться на сайте.', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='files',
            name='content',
            field=models.FileField(help_text='Файл для загрузки, доступный для пользователей сайта.', upload_to='uploads/', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='files',
            name='published',
            field=models.BooleanField(default=False, help_text='Отметьте, если файл готов к публикации и должен быть доступен на сайте.', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='files',
            name='subsection_id',
            field=models.PositiveIntegerField(help_text='ID объекта контента, к которому относится файл.', verbose_name='ID подраздела'),
        ),
        migrations.AlterField(
            model_name='files',
            name='subsection_type',
            field=models.ForeignKey(help_text='Тип контента, к которому относится файл.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип подраздела'),
        ),
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(help_text='Название файла, отображаемое на сайте.', max_length=255, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Полный текст подраздела, отформатированный с помощью редактора.', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='published',
            field=models.BooleanField(default=False, help_text='Отметьте, если подраздел должен быть доступен на сайте.', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='section',
            field=models.IntegerField(help_text='Номер раздела, связанного с материалами для аккредитации.', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='title',
            field=models.CharField(help_text='Название подраздела с материалами для аккредитации.', max_length=255, verbose_name='Название подраздела'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время публикации новости.', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(help_text='Полный текст новости, включающий все важные детали.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение, представляющее новость.', null=True, upload_to='news_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Основной заголовок новости, который будет отображаться на сайте.', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Полный текст подраздела, отформатированный с помощью редактора.', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='published',
            field=models.BooleanField(default=False, help_text='Отметьте, если информация должна быть доступна на сайте.', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='section',
            field=models.IntegerField(help_text='Номер раздела, к которому относится организация.', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(help_text='Название подраздела с информацией об организации.', max_length=255, verbose_name='Название подраздела'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, help_text='Фактический адрес организации, который будет отображаться на сайте.', null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='block1_name',
            field=models.CharField(help_text='Укажите название первого блока информации на главной странице.', max_length=100, verbose_name='Название первого блока'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='block2_name',
            field=models.CharField(help_text='Укажите название второго блока информации на главной странице.', max_length=100, verbose_name='Название второго блока'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='block3_name',
            field=models.CharField(help_text='Укажите название третьего блока информации на главной странице.', max_length=99, verbose_name='Название третьего блока'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Укажите контактный email адрес для связи с администрацией сайта.', max_length=254, null=True, verbose_name='Контактный email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='Ссылка на страницу сайта в Facebook.', null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Ссылка на страницу сайта в Instagram.', null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Загрузите изображение, которое будет отображаться как логотип сайта и иконка браузера (favicon).', null=True, upload_to='settings/', verbose_name='Логотип (фавикон)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='main_title',
            field=models.CharField(help_text='Основной заголовок сайта, который будет отображаться на главной странице.', max_length=100, verbose_name='Главный заголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Основной контактный номер телефона для связи с администрацией.', max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(help_text='Полное название сайта, которое будет отображаться в заголовке браузера и в разделе информации о сайте.', max_length=255, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='subtitle',
            field=models.CharField(help_text='Подзаголовок сайта, который дополнит основной заголовок на главной странице.', max_length=100, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_link',
            field=models.URLField(blank=True, help_text='Ссылка на страницу сайта в Twitter.', null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Полный текст подраздела, отформатированный с помощью редактора.', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='published',
            field=models.BooleanField(default=False, help_text='Отметьте, если подраздел должен быть доступен на сайте.', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.IntegerField(help_text='Номер раздела, к которому относится этот подраздел.', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='title',
            field=models.CharField(help_text='Название подраздела, которое будет отображаться на сайте.', max_length=255, verbose_name='Название подраздела'),
        ),
    ]
