# Generated by Django 5.1.1 on 2024-11-05 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('content', models.FileField(upload_to='uploads/', verbose_name='Содержание')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано?')),
                ('subsection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
