# Generated by Django 5.1.1 on 2024-11-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_base_options_alter_materials_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='published',
            field=models.BooleanField(default=True, help_text='Отметьте, если информация должна быть доступна на сайте.', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='files',
            name='published',
            field=models.BooleanField(default=True, help_text='Отметьте, если файл готов к публикации и должен быть доступен на сайте.', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='published',
            field=models.BooleanField(default=True, help_text='Отметьте, если подраздел должен быть доступен на сайте.', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='published',
            field=models.BooleanField(default=True, help_text='Отметьте, если информация должна быть доступна на сайте.', verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='published',
            field=models.BooleanField(default=True, help_text='Отметьте, если подраздел должен быть доступен на сайте.', verbose_name='Опубликовано?'),
        ),
    ]
