# Generated by Django 5.1.1 on 2024-11-05 18:42

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'Специалистам', 'verbose_name_plural': 'Специалистам'},
        ),
        migrations.AlterModelOptions(
            name='materials',
            options={'verbose_name': 'Специалистам', 'verbose_name_plural': 'Специалистам'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Специалистам', 'verbose_name_plural': 'Специалистам'},
        ),
        migrations.RemoveField(
            model_name='base',
            name='subsection_ptr',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='subsection_ptr',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='subsection_ptr',
        ),
        migrations.AddField(
            model_name='base',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=2, verbose_name='Содержание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
        migrations.AddField(
            model_name='base',
            name='section',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base',
            name='title',
            field=models.CharField(default=2, max_length=255, verbose_name='Название подраздела'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=2, verbose_name='Содержание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
        migrations.AddField(
            model_name='materials',
            name='section',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='title',
            field=models.CharField(default=2, max_length=255, verbose_name='Название подраздела'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=2, verbose_name='Содержание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
        migrations.AddField(
            model_name='organization',
            name='section',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='title',
            field=models.CharField(default=2, max_length=255, verbose_name='Название подраздела'),
            preserve_default=False,
        ),
    ]
