# Generated by Django 5.1.1 on 2024-11-03 22:21

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=2, verbose_name='Полное описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=2, max_length=500, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
