# Generated by Django 5.1.1 on 2024-10-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('block1_name', models.CharField(max_length=100)),
                ('block2_name', models.CharField(max_length=100)),
                ('block3_name', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Логотип')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
