# Generated by Django 5.1.1 on 2024-12-04 22:17

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_base_published_alter_files_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMedicalPrevention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(help_text='Номер раздела, связанного с базой информации для специалистов.', verbose_name='Раздел')),
                ('title', models.CharField(help_text='Название подраздела с информацией для специалистов.', max_length=255, verbose_name='Название подраздела')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Полный текст подраздела, отформатированный с помощью редактора.', verbose_name='Содержание')),
                ('published', models.BooleanField(default=True, help_text='Отметьте, если информация должна быть доступна на сайте.', verbose_name='Опубликовано?')),
            ],
            options={
                'verbose_name': 'База',
                'verbose_name_plural': 'База',
            },
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение, представляющее событие.', null=True, upload_to='event_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение, представляющее новость.', null=True, upload_to='news_images/', verbose_name='Изображение'),
        ),
    ]
