# Generated by Django 5.1.1 on 2024-11-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_base_options_alter_materials_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materials',
            options={'verbose_name': 'Materials', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organization'},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={'verbose_name': 'SubSection', 'verbose_name_plural': 'SubSection'},
        ),
    ]
