# Generated by Django 5.1.1 on 2024-11-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
