# Generated by Django 5.1.1 on 2024-11-03 23:22

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликованно?')),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название подраздела')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание подраздела')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликованно?')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='core.section', verbose_name='Раздел')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
