# Generated by Django 5.1.1 on 2024-11-03 23:48

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_section_subsection_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', django_ckeditor_5.fields.CKEditor5Field(max_length=500, verbose_name='Краткое описание')),
                ('full_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Полное описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='is_published',
        ),
        migrations.AddField(
            model_name='section',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
        migrations.AddField(
            model_name='subsection',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название подраздела'),
        ),
    ]
