# Generated by Django 5.1.1 on 2024-11-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_remove_section_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
