# Generated by Django 5.1.1 on 2024-11-04 16:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_base_materials_organization_delete_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
    ]
